services:
  app-ubmager:
    build:
      context: .
      dockerfile: Dockerfile
    user: "108:111"
    container_name: ubmager_app
    restart: unless-stopped
    working_dir: /var/www/UBMagerAPI
    env_file:
      - ./.env
    volumes:
      - laravel_storage:/var/www/UBMagerAPI/storage
      - laravel_cache:/var/www/UBMagerAPI/bootstrap/cache
    networks:
      - shared-network
  web-ubmager:
    image: nginx:alpine
    container_name: ubmager_web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=dev-api.ubmager.shop
      - LETSENCRYPT_HOST=dev-api.ubmager.shop
      - LETSENCRYPT_EMAIL=ahmadfauzanroziqin@gmail.com
    volumes:
      - .:/var/www/UBMagerAPI
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-ubmager
    networks:
      - shared-network
  worker-ubmager: 
    build:
      context: .
      dockerfile: Dockerfile
    user: "108:111"
    container_name: ubmager_queue
    restart: unless-stopped
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    env_file: ./.env
    working_dir: /var/www/UBMagerAPI
    volumes:
      - laravel_storage:/var/www/UBMagerAPI/storage
      - laravel_cache:/var/www/UBMagerAPI/bootstrap/cache
    networks:
      - shared-network 
    depends_on:
      - app-ubmager
  scheduler-ubmager:
    build:
      context: .
      dockerfile: Dockerfile
    user: "108:111"
    container_name: ubmager_scheduler
    restart: unless-stopped
    command: php artisan schedule:work
    env_file: ./.env
    working_dir: /var/www/UBMagerAPI
    volumes:    
      - laravel_storage:/var/www/UBMagerAPI/storage
      - laravel_cache:/var/www/UBMagerAPI/bootstrap/cache
    networks:
      - shared-network
    depends_on:
      - app-ubmager
networks:
  shared-network:
    external: true

volumes:
  laravel_storage:
  laravel_cache: